sudo: required
language: node_js
node_js:
- '12'
before_script:
- npm install
script:
- npm run test
deploy:
  provider: npm
  email: mauriceprivat98@gmail.com
  api_key:
    secure: "j+ItNzAgD37JuQEMLikuEm5gWq64HUchtTp3LFKolk2D+k3FQsiFWfy3VkNY2WkAzf4td+w8rOnHMZQJRH45s77DmzRKpM53GsuE412O5kKcgIiiSCCanR7kbQTTix72MFMwwJ3g8l6MPstL0TaHeFsEAD5ckfA2fTvsoiHbTjgVdUW5MLpBFxnDrGvJMwoGbiFXbA7OM2grCQ4GtGRCdyuwUa4puJ6S6nqEeUbWUd9rfNqVP5PgxHApeJuWTb5D5nItReU9wiC4tK5NmRUqlwMQrXZ0hrVCNcVGg5CIAg5ZAH2bhp6+AIMz1tBx6shDe84/TgAw0sKMWLaOcCcCA5s65hnxNJKZlb56ZqUuy+Rm5Z1QyjgJstJl8A5SjxZUMhAYVn5mkSV1/yM7RTXR4TJMLnFxPBKW2u9osKV3ifJ+TpOyn/bsKogiGvktW1tmPN9iR3kjS5rrm0sKdkJyVL9l9aGiPilLckyxc83KcwaMI2uBRo3FNgq36wIpyLalCdakU9J5QpVwXm0QDPiPRPf5M0sA3ktEg+q5mcDUWp4oG8aGleS9qL/dEwE8jkVtYWEgAjaBeoVMzwG9X8pLxpieXknKp6ujy+KzDw2yj7UYEyAF1M75dzbYwzsrL74dEZunLVKcC+Bs3SS7mgJcFubqMGY+6F9PoDrf0+qtrhk="
  on:
    tags: true
